### ISSUE TITLE
UBW 搬迁到主服的相关问题

### ISSUE THREAD

**Issue by Subilan** [sotapmc/Discussion#3]
我觉得 UBW 的出现是为了更好地建筑，但是一些玩家可能会把它当成某种可以用创造建造*满足自己<u>**生存需求**</u>的建筑*，再用金钱买回的模式。

我认为应当对此加上限制。比如一些生存电路器械，也许在生存模式下制造会很复杂，因为考虑到多方面的因素（怪物、原材料），但是如果放在 UBW 里面建造，然后掏钱买回去，似乎比生存里建造要划算的多。

~~目前 WE 搬迁的价格是 0.5cpb，而生电机器并不如正经建筑那样占据空间，所以完全可以靠节省空间的方式来压低自己要付的价格，使低价购入自己用创造模式建造的机器。同时还要考虑到每个方块的价格参差不齐，例如钻石块和泥土。不过 0.5c 一个方块这样的定价也是合理的，因为是针对一整个建筑来说，就跟圈地一样；但是如果一些玩家将这个「建筑」的概念换成了「资源」，那么 0.5c 就显得非常 bug。~~

我认为这样下去有多个风险

- 并不能很好地激起玩家的建筑热情，反而*可能*导致 UBW 成为一个玩家用金钱获得机器的好方式。
- 一些复杂的大型产能机器花大价钱买到主服后，可能导致生产力过剩，降低游戏热情。
- 玩家也许可以在建筑中藏入一些资源方块，搬迁后即可快速获得资源。

当然，上面的有关「游戏兴趣」方面的内容大可以看作是杞人忧天。我个人的观点，改进措施是

- 拒绝所有非像素画或正经建筑的搬迁需求，UBW 只能用来测试红石机械而不能用来走捷径；
- 在搬迁建筑前对建筑的内容进行全面检查，列出一个不接受方块名单，可以使用 `//replace diamond_block air` 之类的指令实现；
- 当玩家需要将一些特殊的方块，例如末地传送门，用于装饰时，必须提前说明。

仅仅是个人观点~ 因为我不是 sotap 管理，所以还需要进一步讨论。

**Comment by Subilan** [comment]
另外，也许这些默认情况下已经有了相关的规定，不过还是觉得写出来会比较好~

**Comment by WindSpiritSR** [comment]
我觉得搬迁的时候可以先统计建筑中使用的各种方块，要求玩家在主世界中按比例提供相应的资源（或提供全部资源，但应适当降低搬迁费用）

**Comment by Subilan** [comment]
> 我觉得搬迁的时候可以先统计建筑中使用的各种方块，要求玩家在主世界中按比例提供相应的资源（或提供全部资源，但应适当降低搬迁费用）

赞同，这样可以有效避免这个搬迁的过程彻底沦为了「向自己购买建筑」的样子 ![1A9 E$EC6N2 5 Y2O)$_UDC](https://user-images.githubusercontent.com/36447840/81560861-d2ef6980-93c4-11ea-8231-895cd74e3c9a.jpg)

**Comment by Subilan** [comment]
手动 at + Assign 大佬们
@constant137 @Sapherises @Remind233

**Comment by Subilan** [comment]
以及我认为不应该允许生存模式下「不应存在」的方块进行搬迁，例如隐形基岩（barrier）。当然，公共设施，比如跑酷这种，搬到主服去另当别论 ![{F}SQO_E9%Q2@~G%E(835ZQ](https://user-images.githubusercontent.com/36447840/81564572-86a72800-93ca-11ea-8768-61e2b68e6374.png)

**Comment by constant137** [comment]
首先我认为在建筑服里面，玩家建造的内容不受限制，但是可以搬运到主服的建筑是需要限制的。这些可以搬运的建筑应该只限于“公用建筑”，也就是建筑者拥有对建筑的“专利”权，但不是“所有”权。在这个条件下，可以选择WE搬运的时候不收费；
私人的建筑也是可以建造的，但是搬运的时候需要进行估价；
红石机器一律不许搬运，对于机器来说，建筑服只起到测试的作用。
最后举一些公用建筑的例子：城市或者是房屋组、景点、娱乐设施、比赛地图等。

**Comment by Subilan** [comment]
同意常姐姐的观点嗷，按照常姐姐说的方法搬迁，即公共建筑可以考虑不收费，私有建筑按照一定标准估价（当然，单纯的 0.5cpb 也可以），这样以来可以促进一些建筑爱好者的热情。而要区分公共建筑和私有建筑，就是看它们的所有者。

比如，如果是公共建筑，那么将由服务器统一圈地，但是会注明原作者是哪位玩家；而如果是私有建筑，我们就无需考虑圈地这一块，只负责搬迁，圈地的事情由玩家自己负责。

对于公有建筑，理论上可以允许使用所有方块，因为这些方块最终只起到了「公共功能性」或者单纯的「装饰性」作用，并没有什么影响；而对于私有建筑，矿物块、末地传送门、隐形基岩之类的方块，就不应允许搬迁。

---

__*cpb*__: coins per block

**Comment by Sapherises** [comment]
ubw服的初衷其实是一个创造服，但由于2个因素的考虑之后的定位并不完全是创造服：
 • 怕其有可能导致玩家去创造服建筑而主服很少有优秀建筑了
 • 怕有可能大家并不care创造服所以大家都在主服而创造服被nbcs了
由于这两个方面的考虑，我允许玩家到创造服建筑以后花钱搬运到主服去，这样大家也就会care这个新服务器，而主服也会因为这样继续会出现优秀建筑。
当前ubw的定位是创造+测试建筑和机器。规则没有创造服那么严格（比如可以随心所欲的建造烂尾楼和烂尾机器）等于就是一个测试机器和建筑随心所欲的服务器。
当前，要从ubw搬迁到主服需要支付2种费用（我之前在公告有写）：那就是整个搬迁建筑的所有材料的费用（按照主服物价来结算）和搬迁we费用（0.5c/格）
那么，ubw和在主服建东西有什么区别呢？很多玩家都有云宝宝，那么ubw里面可以飞这个特点对于很多玩家来说并不吸引人，那么ubw最大的区别就是在ubw里面建东西可以直接得到想要的材料，而主服里面需要玩家去商店购买，然后再带回家建筑，主要简化的就是建材获得这一步骤。这样让建筑玩家更轻松的获得想要的建材也可以激发建筑玩家建造建筑的热情，同时增加花费coins的途径，可谓是一举两得。

现在目前看来ubw在未来可能会被沦为一些玩家轻松建筑生电机器的方式（这一途径是否会被滥用还需要进一步观察）
以及subilan的问题
1. 玩家也许可以在建筑中藏入一些资源方块，搬迁后即可快速获得资源。
这个的确我没有考虑到，就像su提供的建议，在we之前检查建筑和使用指令排查一些物品来解决这个问题
2. 一些复杂的大型产能机器花大价钱买到主服后，可能导致生产力过剩，降低游戏热情。
可以规定一些大型的资源机器适当增加费用，将整个we区域设为全充满方块来we计费，而不是排除掉空气方块，另外观景建筑类可以适当根据建筑质量给折扣。
3. 并不能很好地激起玩家的建筑热情，反而可能导致 UBW 成为一个玩家用金钱获得机器的好方式。
这个问题我没有get到点，因为我在考虑了以后觉得没有这个问题...

**Comment by Subilan** [comment]
> 一些复杂的大型产能机器花大价钱买到主服后，可能导致生产力过剩，降低游戏热情。
可以规定一些大型的资源机器适当增加费用，将整个we区域设为全充满方块来we计费，而不是排除掉空气方块，另外观景建筑类可以适当根据建筑质量给折扣。

也就是说仍然会允许搬迁机器，只是贵了点吗...？我认为对于机器的搬迁应当禁止，UBW 对于红石来说只是一个测试的场地。

针对我的这一条

> 并不能很好地激起玩家的建筑热情，反而可能导致 UBW 成为一个玩家用金钱获得机器的好方式。

是因为我觉得如果 UBW 是「所有建筑皆可搬」的无限制创造服务器，那么这个服务器就不存在一个创造的独立玩法了，而是一个玩家的工具，用于快速建造的工具。事实上，把 UBW 和主服结合在一起，初衷是为了解决 NBCS 的问题，所以加上了一些额外的机制；但是如果这个机制过于放纵，玩家也许不会再把它当成一个独立的服务器看待——但最初开放 UBW 不是为了让它成为一个独立的服务器吗？

我想象中的 UBW 应该是玩家自由创造的世界，玩家可以无忧无虑地在里面建筑，自由组合建筑群，当然也可以独立挑选合适的生物群系、地点（譬如山顶）来建筑。但实际上现在我对 UBW 的理解更加倾向于一种超平坦（虽然不是）的随处乱建，互不关联，最后的结局都是搬迁到主服务器或者留在 UBW 里面吃灰？

🤔

**Comment by Sapherises** [comment]
> 我想象中的 UBW 应该是玩家自由创造的世界，玩家可以无忧无虑地在里面建筑，自由组合建筑群，当然也可以独立挑选合适的生物群系、地点（譬如山顶）来建筑。但实际上现在我对 UBW 的理解更加倾向于一种超平坦（虽然不是）的随处乱建，互不关联，最后的结局都是搬迁到主服务器或者留在 UBW 里面吃灰？

Good Question，对于ubw服，我纠结了很久，怎么才能让玩家care它，因为如果完全定位为一个建筑服的话，那就直接等于是小众化的服务器了，因为建筑好的玩家依然是少数，大部分玩家还是停留在从b站看建筑教程来建房子甚至直接火柴盒的水平，打造一个建筑服，按照当前sotap的服情，到最后很大概率还是沦为nbcs的鬼服，所以我才开放和主服的联系，以及允许玩家到这里来“乱搭乱建”测试机器。那么如何平衡好创造和测试是个很头疼的问题，开放搬迁到主服完全就是为了吸引玩家来ubw服。因为比如要给玩家一个动力和来的理由，单纯一个创造服并且和主服不互通是吸引不了太多玩家的，而且要来这个服务器建筑为什么我不去主服建筑呢？哪怕主服的建筑难度更高一点？这就是我之前提到的担心的其中一点，因为要建立一个你理想中的那个ubw的话就需要对ubw有严格的限制：仅仅建筑专用，并且不允许测试建筑用，除非自己处理掉测试完后的烂尾楼。
正因为大部分玩家来这个服主要就是为了搬到主服去或者来这里测试烂尾楼，所以现在的确更偏向于一个超平坦测试服了，但是我之所以不弄成超平坦就是我依然希望玩家把这个服当作一个“建筑服”来建，这样他们就可以依照生物群系来建筑。我现在甚至都还没考虑好这个服务器是否要定期重置地图。
要做好这两个平衡，我当前是这个想法：
1. 杜绝一些过于生电化的机器we到主服，但是可以来这边测试。
2. 允许一些不太生电的机器，比如刷铁机和村民塔
3. 开2个世界，一个世界永不重置，当作创造服来要求，一个世界测试世界，可乱搭乱建，定期重置
4. 创造世界是默认地形，测试世界超平坦
5. 允许we的机器类像我刚刚说的那样，还要适当调高价格
6. 建筑类根据水平来适当给折扣

**Comment by Subilan** [comment]
其实话说回来，如果给玩家开创造来建造一个新的建筑群，的确没有什么意义——除非是为了特地建造场景供宣传使用，不然真的想不到有什么实际的作用了。那么纠结再多又回到了 UBW 服务器本质的问题来...... 似乎没有什么讨论的价值。

就按照所说的

> 1. 杜绝一些过于生电化的机器we到主服，但是可以来这边测试。
> 2. 允许一些不太生电的机器，比如刷铁机和村民塔

允许部分生电机器也好，否则会让一些玩家彻底对 UBW 丧失兴趣。对于

> 3. 开2个世界，一个世界永不重置，当作创造服来要求，一个世界测试世界，可乱搭乱建，定期重置
> 4. 创造世界是默认地形，测试世界超平坦
> 5. 允许we的机器类像我刚刚说的那样，还要适当调高价格
> 6. 建筑类根据水平来适当给折扣

这几条都比较合理，同时也符合我的预期~ 感谢sa姐给出这么精彩的回复哦。

**Comment by constant137** [comment]
那像我之前的那种提议sa怎么看。甚至可以选择给建公共建筑的玩家一定的奖励，coins或者称号啥的

**Comment by Subilan** [comment]
~~如果没有什么问题的话，可以 close 了呢。~~ 啊既然常姐姐还有问题，我们继续吧。

如果有兴趣的话也许可以讨论

- UBW 服务器的性能问题及其优化
- UBW 服务器的插件完善程度
- 如何保护建筑免受破坏
- 允许玩家使用的指令。
    - 目前如果只允许使用 `/tpa`、`/setwarp` 这类，有的时候会让一些*真正的*「高玩」感到束手无措。也许可以提供给部分玩家免费或付费的（服内）WE 权限，或者 setblock 权限
    - 也许 UBW 用来测试命令方块和活动也是一个不错的 idea......? `->` 一般玩家也可以申请在 UBW 里面调试命令方块

**Comment by Subilan** [comment]
> 那像我之前的那种提议sa怎么看。甚至可以选择给建公共建筑的玩家一定的奖励，coins或者称号啥的

@Sapherises

**Comment by Subilan** [comment]
> 那像我之前的那种提议sa怎么看。甚至可以选择给建公共建筑的玩家一定的奖励，coins或者称号啥的

称号可以，但是不要让它烂大街了。可以尝试给这些建筑的玩家一个统一的称号，而非定制；同时可以设定一个期限。往大了说，其实很多之前玩家的称号都可以设定期限... 只是给的时候都给的是永久，所以才会有这样的顾虑。

一个简单的实现

```
> lp user Subilan permission settemp deluxetags.tag.subilanonly 2 day
```

**Comment by Sapherises** [comment]
> * UBW 服务器的性能问题及其优化
> * UBW 服务器的插件完善程度
> * 如何保护建筑免受破坏

UBW一般就是建筑用和测试用，并且玩家同时在线也很少，JD的机子性能完全够用，之前30+人在线pvp不也抗住了吗？所以我不太担心性能的问题，优化的话，我会专门研究一下，比如测试世界直接完全禁止生物和怪物生成，以及禁用地狱来减少很多不必要的性能损耗

UBW插件的话，除了ess全家桶，我目前就安装了lp和we，我想，对于一个建筑和测试的服务器来说完全够用了，再多就多余了，还会消耗多余性能

保护的话，有个coi足以。

**Comment by Sapherises** [comment]
> 许玩家使用的指令。
> * 目前如果只允许使用 `/tpa`、`/setwarp` 这类，有的时候会让一些_真正的_「高玩」感到束手无措。也许可以提供给部分玩家免费或付费的（服内）WE 权限，或者 setblock 权限
> * 也许 UBW 用来测试命令方块和活动也是一个不错的 idea......? `->` 一般玩家也可以申请在 UBW 里面调试命令方块

可以考虑呢

**Comment by Sapherises** [comment]
> 选择给建公共建筑的玩家一定的奖励，coins或者称号啥的

也可以考虑呢，我现在是打算给一个统一的称号

**Comment by AnonymityW** [comment]
interesting
