### ISSUE TITLE
未来几个月的游戏性更新规划安排

### ISSUE THREAD

**Issue by Sapherises** [sotapmc/Discussion#4]
> **以下安排仅仅是初步安排和构想，可实行性未经过充分的考虑。**

**5月**

计划新建成2个场景：黄金海岸和巴黎城西  

黄金海岸主要2个建筑：慈善之家和假日小屋

- 慈善之家的用途：  

我是想在其设置一个可以随机选定物品进行随机收购的一个收购点，来帮助那些贫穷的玩家（无论新老玩家）判断贫穷一般是根据：薄荷币、coins、实物财产三个方面来判断。  
玩家也可以主动申请救助。设置一个捐助箱，其他玩家可以真正将自己不需要的物品（非垃圾）放入，将其分发给贫困玩家。  
其他玩家甚至可以捐献coins到慈善之家基金里，会根据情况无偿发放给贫困玩家。coins是其他玩家花钱购买“爱心券”，目前暂定1000/张，然后爱心券再发给贫困玩家来兑换，以此实行coins的捐助。  

- 假日小屋的用途：  

在慈善之家捐助了以后可以得到若干兑换券，可以在假日小屋兑换家具和武器等物品。

巴黎城西主要建筑：市政厅、蚂蚁商城、邮局、报社

- 市政厅的用途：玩家设置年龄的地方，退服玩家物品拍卖以后会在此举办，以后活动线上报名等等各种事物也在这里。

- 邮局：新的打工点

- 报社：新的打工点，也计划未来出个sotap周刊？月刊？

- 蚂蚁商城：卖神秘新插件物品的地方。

**6月**

计划新建成3个场景：干巴巴湿地、梦乡、不死光年（复原）  

干巴巴湿地主要建筑：魔法树屋

- 魔法树屋主要用途：

1. 会上线新的扩展附魔，魔法树屋可以售卖这些新附魔。
2. 会上线一个SVP玩家专属的武器工具升级机制，来代替突破附魔。
3. 在这里可以兑换在“梦乡”场景采集的“元素”来兑换年龄增长药剂。当年龄到一定以后比如18，可以解锁一些权限。

- 梦乡主要用途：  
一个新的独立世界，只能从“不死光年”的特定入口进入。  
类似于一个宇宙的世界，里面有一些“星球”，上面有各种其他矿物还可以采集“元素”，会有特定的收购新矿物的npc。  
该世界同时限定时间和物品进入！  

- 不死光年主要用途：

1. 提供进入梦乡的唯一入口
2. 进入梦乡需要佩戴一个特质的保护罩才能进入，在不死光年可以售卖。
3. 可以在上线之前引入一个限时任务来让大家发现不死光年，制作一个解密活动，活动可以得到称号”不死之光“，只有不死之光称号的人才能去不死光年（临时限制）
4. Pro和SVP可以不用佩戴保护罩进入梦乡。

**7月**

- 举办夏日祭
- 举办So运会
- ”7月流火“活动

**8月**

上线”百花园“场景
百花园收购花和蜂蜜，收购价格每天自动更新。
同时下线之前的蜂巢插件，改为原版蜂巢

**其他说明**
我计划从6月开始，每个月更新一种月度限定的活动，特殊的玩法。月份过了以后就下线，比如我计划在6月上线彩虹活动，到时候玩家就可以自定义之前我在群里发的那种好看的彩虹，同时彩虹下方自动生成一个npc指引玩家去探索宝藏（类似于藏宝图的）
7月是流星坠落，坠落的地方有很多宝藏，同时会生成”守卫者“。
以上2个都有插件实现效果。

**目前需要自写插件实现的效果**
年龄：根据玩家在线时间来增长年龄，玩家也可以通过服用特定药水来增长年龄，年龄达到一定以后解锁一些特权”比如买车权限“我会上线新载具插件。

**Comment by Subilan** [comment]
sa姐老盒粉了

**Comment by Sapherises** [comment]
里面不是还有很多奥比岛的场景🐎

**Comment by Sapherises** [comment]
> sa姐老盒粉了

这样也很”RPG Style“不是🐎？虽然冰箱还会单独制作RPG内容罢了

**Comment by Sapherises** [comment]
建设的地方很多，因此建设难度很大，仅仅管理组来根本不够，很多场景需要玩家一起来帮忙建设了

**Comment by Subilan** [comment]
年龄的话... 说说我的想法，常姐姐 @constant137 轻喷

首先不可否认的是，用 YAML 存储每个玩家的年龄数据

```yaml
Remind_Z: 0
Constant137: 99
Sapherise: 130
```

如果直接根据所说的

> 年龄达到一定以后解锁一些特权”比如买车权限“

将会导致实现起来很困难，因为这样必须使用对方的 API。对此，我的想法在配置文件中增加一个选项，允许配置到达多少岁数后执行什么指令。简单的例子：

```yaml
age_awards:
    "1":
        - "lp user %username% permission set essentials.tpa true"
        - "give %username% diamond 3"
    "20":
        - "lp user %username% permission set essentials.back true"
        - "give %username% diamond_block 3"
     # ...
```
这样也显得更灵活，因为可以自定义执行的指令。

同时还有一些其它有趣的机制可以考虑：

- 允许设定一个最大年龄
- 允许设定达到最大年龄后触发的事件
    - 是进入下一轮回？轮回与轮回之间的奖励不一样？
    - 还是就这么定格在最大年龄不变？
    - 还是...？
- 新手期可以不再拘泥于 7 天的时限，而是让玩家在成长 X 岁后自动吊销，这样可以避免玩家不上线导致错过机会——毕竟是**新手**期。
- 达到 24 岁的时候会发生什么？
- ...

**Comment by Sapherises** [comment]
> * 允许设定一个最大年龄
> * 允许设定达到最大年龄后触发的事件
>   
>   * 是进入下一轮回？轮回与轮回之间的奖励不一样？
>   * 还是就这么定格在最大年龄不变？
>   * 还是...？

可以的，我建议设定一个130岁的最大年龄，然后刚刚常女士讨论可以制作两种药剂，一个喝了减一岁，一个喝了加一岁。同时到达一定的年龄段以后给予玩家一些buff，年龄大了可以给一些DEBUFF，这样，这样减年龄的药水就有用武之地。但是默认在线多少时长就会增加一岁，我认为在线5小时左右加一岁比较可，大部分玩家一天玩服务器的平均时间就是5h，这样到7岁就可以关闭新手保护了。

**Comment by constant137** [comment]
> - 新手期可以不再拘泥于 7 天的时限，而是让玩家在成长 X 岁后自动吊销，这样可以避免玩家不上线导致错过机会——毕竟是新手期。

这个很棒。

关于年龄的设定其实有很多可以深挖的点，首先是各个年龄段的BUFF:
- 幼年时期，类似幸运、迅捷、虚弱这样的BUFF，比较贴近小孩。
- 青壮年时期，挖掘效率提升，力量，抗性等，但是光这样的确是贴近了青年人的特点，但是会不会有点影响平衡导致大家最后都选择控制年龄在这个阶段。
- 老年时期，缓速和失明，不过因为~~长者的~~智慧，也许可以提高附魔的幸运度？
总之每个时期都需要有好的BUFF以及不好的BUFF，不能让某个年龄段成为服务器的DSSQ。

然后每个年龄的划分是不是应该以现实生活中的划分为标准？如果是这样可能会出现幼年、老年期过短，青年时期过长。但是平均的划分又不是很贴近实际。所以我的初步想法是按照现实生活中的年龄划分的五分之一来定MC的游戏年龄段，这样年龄的切换也会更迅速，可以在短时间内体验到更多的内容，而且可以适当促进药水的购买。（年龄切换更快了，所以需要更加频繁的调节自己的年龄）

最后，是否需要设定死亡，死亡以后如果是从头开始增长年龄的话，就相当于是免费的年龄倒退（不要药水），这么看来保留这个轮回的设定是挺合理的，游戏内总是需要一些不要氪金加肝的要素的。

轮回是否需要奖励，还是就记录一个玩家在服务器内已经几世？可以作为称号自动给予玩家。如：【SUBILAN五世】

**Comment by Sapherises** [comment]
> 最后，是否需要设定死亡，死亡以后如果是从头开始增长年龄的话，就相当于是免费的年龄倒退（不要药水），这么看来保留这个轮回的设定是挺合理的，游戏内总是需要一些不要氪金加肝的要素的。
> 
> 轮回是否需要奖励，还是就记录一个玩家在服务器内已经几世？可以作为称号自动给予玩家。如：【SUBILAN五世】

你这么一说，那肯定玩家死亡以后不能影响年龄了。另外我认为直接设置一个最大年龄，到达以后不会再继续增长年龄即可。因为设置轮回了以后要考虑，在到达极限年龄了要不要设置一个什么状态比如玩家死亡（但是保留背包），不可能仅仅是把年龄重新不声不响的归0吧？那重回的意义是？而且之前提到了重回以后等于免费归0了年龄，会不会被人“滥用”这个机制？

**Comment by Sapherises** [comment]
另外既然有年龄了，我们可以让玩家到达指定年龄以后才能结婚，买车之类的

**Comment by Subilan** [comment]
这样可以把年龄机制同时作为一个衡量服务器玩家服龄的标准，玩的时间越久福利越多。

为了使这个服龄可靠，我不想让年龄的自动增长仅凭借时间来衡量，否则这样会使挂机的情况更加泛滥，而且使数据失去可信度。我认为可以创造一个公式，跟游戏内的经验、杀怪数量、杀动物数量、走路路程等搭配在一起，然后混杂着在线时间来综合衡量。如果只是挂机的话，年龄并不会变化。

因为现实生活中年龄增长的同时也伴随着个人履历的增长，如果没有履历那么增长年龄也没有用。

增岁和减岁药水不能滥用，因为这直接影响到一个玩家能够享受的权益，需要进一步考虑，例如可以限制只能在某个年龄段使用，或者使用以后加入什么 DEBUFF，甚至撤销某些权限。

**其实我个人更倾向于改成「增速生长」和「减速生长」药水。**增速生长可以适当降低年龄生长所需要的杀怪数量、经验等。同时我还想知道药水的持续时间是多久。

至于

> 轮回是否需要奖励，还是就记录一个玩家在服务器内已经几世？可以作为称号自动给予玩家。如：【SUBILAN五世】

我当初想轮回就是避免 1000 岁这种离谱情况的产生，如果出现了二十世、五十世怎么办...？需要进一步讨论。不过目前想想其实 1000 岁也可以，但是就变味了——跟等级一样。我们需要想办法发挥「年龄」这个特殊的概念。

对于各个年龄段的 BUFF，我认为没必要。因为年龄设计出来是为了增加权限上的东西，让玩家能够访问更多游戏玩法。如果再根据不同的年龄加入 BUFF 或者 DEBUFF，即使这符合人类的正常逻辑，也似乎不能给游戏带来实质性的提升，反倒可能引来滥用的行为。同时应当确保年龄越高越受益的原则，理由就是上文中「年龄即服龄」的观点。

我认为当前需要讨论的就是

- 如何处理年龄的最大限制的问题。
    - 如何显示年龄，或者不显示？
    - 是否采用轮回制度，还是定格年龄？
- 是否应该根据年龄给予「元老玩家」一些「特殊」的奖励？
- 如何解决服务器现有玩家在安装上插件后由于履历不足无法操作的问题

针对第三点，提出这个问题的缘由是

- 根据上文所述，年龄的增长不再只是需要时间，而是需要履历和时间，因此我们无法单凭现有玩家玩服务器的时间来直接通过指令设置年龄（`/setage`）；
- 如果我们不去设置一些低龄和高龄之间的权限差异，可能就会丧失这部分内容的乐趣，插件也就不会往这方面发展；但是如果设置了，就会导致现有玩家的问题。

不知各位怎么看
@constant137 @Sapherises

**Comment by Subilan** [comment]
同时为了这个年龄不会太出戏，考虑加入死亡惩罚。其实最合理的是死亡归零，但是这样估计莫得人玩喽。

**Comment by AnonymityW** [comment]
虽然我觉得年龄本身就已经很出戏了，但我选择支持 加油~

**Comment by Sapherises** [comment]
> **其实我个人更倾向于改成「增速生长」和「减速生长」药水。**增速生长可以适当降低年龄生长所需要的杀怪数量、经验等。同时我还想知道药水的持续时间是多久。

其实可以这样做，比如到了什么年龄就自动给什么权限，那么检测低于了该年龄就可以收回那个权限。这样就不会有人无脑的降年龄了。以及就像你说的，可以设定在特定年龄以后才能使用该药水，比如12岁以后。这样可以避免了复杂化，和插件的编写难度。当然也可以直接不允许玩家降低年龄了（如果不设置年龄段buff的话那降低年龄完全没必要）

**Comment by constant137** [comment]
马上断电了，明天接着回复

**Comment by Sapherises** [comment]
> * 如何处理年龄的最大限制的问题。
>   
>   * 如何显示年龄，或者不显示？
>   * 是否采用轮回制度，还是定格年龄？
> * 是否应该根据年龄给予「元老玩家」一些「特殊」的奖励？
> * 如何解决服务器现有玩家在安装上插件后由于履历不足无法操作的问题

第一个问题，我认为目前最简单的办法就是定格一个最大年龄就可，轮回的话就需要考虑轮回以后如何区别轮回玩家和非轮回玩家的年龄？以及，无论是否轮回，到最后都会出现1000岁和50世的情况，这样和QQ等级无疑，所以我认为还是直接定格比较好。

第二个问题，或许可以显示在玩家名后面或者放到menu里面查询指定玩家的岁数？或者显示在头顶的全息上？

第三，肯定会根据年龄来给玩家解锁新权限啊，年龄的意义不就是越大解锁更多权限吗？你所说的元老玩家是年龄很老很老的玩家吗？我不太看懂。。。

第四个问题我也不太懂，因为我是构想的是一开始无论新老玩家全部都是0岁，再来慢慢涨岁数，解锁的权限大部分都为以后新加入的内容，所以我觉得不会太冲突。以及，直接把first join的指令改为设置新加入玩家为新人玩家就可，不再设置临时，然后再把到7岁的玩家设置个解除新人组指令，这样就没什么冲突的了

**Comment by Sapherises** [comment]
> 同时为了这个年龄不会太出戏，考虑加入死亡惩罚。其实最合理的是死亡归零，但是这样估计莫得人玩喽。

其实也可以死亡归零，那么就是体现增岁药剂的作用了，那么药剂就要设置使用一次加一岁，其实这样是最好的可以防止年龄无限增加的方式

**Comment by Subilan** [comment]
> 第三，肯定会根据年龄来给玩家解锁新权限啊，年龄的意义不就是越大解锁更多权限吗？你所说的元老玩家是年龄很老很老的玩家吗？我不太看懂。。。
>
> 第四个问题我也不太懂，因为我是构想的是一开始无论新老玩家全部都是0岁，再来慢慢涨岁数，解锁的权限大部分都为以后新加入的内容，所以我觉得不会太冲突。

你怎么这么容易不懂啊 ![BS2$AY~)ZTT0X5{)X PABX9](https://user-images.githubusercontent.com/36447840/81833365-3074e900-9572-11ea-97f7-cec3c87a2454.png)，直接说自己的想法不就行了？

> 解锁的权限大部分都为以后新加入的内容

因为我原先想的是在服务器现有的基础上做删减，等到满年龄之后才能重新回到目前这种「人人拥有完整权限」的格局。不过，既然解锁的权限都是未来的内容，那么这个问题就已经解决了。

> 以及，直接把first join的指令改为设置新加入玩家为新人玩家就可，不再设置临时，然后再把到7岁的玩家设置个解除新人组指令，这样就没什么冲突的了

这个从提出构想开始就已经考虑到了不需要再提。

> 其实也可以死亡归零，那么就是体现增岁药剂的作用了，那么药剂就要设置使用一次加一岁，其实这样是最好的可以防止年龄无限增加的方式

如果这样的话，我前面所有提出的跟年龄判断机制和年龄即服龄的论断都是白谈。死亡归零必定会让年龄这个机制变得廉价，玩家死后权限直接被剥夺。那么既然丢失年龄如此容易，长大也会很容易，那些权限也会很容易就能得到，当然也会很快丢失，我认为会使插件直接丧失意义。

还是说年龄即服龄，我的设想是想让玩家能够通过长期的**有意义**而非挂机服务器内容的探索，来获得更多的特权，从而提高玩家质量。虽然似乎并不能直接提高玩家质量，至少会让玩家感到新鲜，也会增加游戏性*哪怕一点点*。而不是像某些玩家为了 PTT 奖励疯狂挂机，群里和服务器里一句话也不说，这样是非常没有意义的。

**Comment by Subilan** [comment]
> > **其实我个人更倾向于改成「增速生长」和「减速生长」药水。**增速生长可以适当降低年龄生长所需要的杀怪数量、经验等。同时我还想知道药水的持续时间是多久。
> 
> 其实可以这样做，比如到了什么年龄就自动给什么权限，那么检测低于了该年龄就可以收回那个权限。这样就不会有人无脑的降年龄了。以及就像你说的，可以设定在特定年龄以后才能使用该药水，比如12岁以后。这样可以避免了复杂化，和插件的编写难度。当然也可以直接不允许玩家降低年龄了（如果不设置年龄段buff的话那降低年龄完全没必要）

我打算直接放弃年龄段 BUFF，因此不会有降低年龄的药水。

**Comment by Subilan** [comment]
还是说到轮回这个问题上来，目前讨论出的结果我个人比较倾向于一个静态的最高年龄限制，到达此年龄后不再变动，但是仍然留有灵活的空间。因此服务器可以先设置一个基本年龄，例如 100，当出了新的内容**必须**在年龄限制上做手脚时，就可以一步步扩大，当然我们自己心里得有数到底最高可以到多少。

不过插件是自由的，哪怕 1000、10000 都不会有任何影响，只是比较出戏，仅此而已。

至于为什么静态，因为
- 我们针对不同的年龄所给予的奖励是有限的，因此在没有奖励可给的情况下让玩家滞留在一个年龄是合理的；
- 玩家不至于重新从 0 开始，导致之前所有苦苦积累的经验、方块挖掘、生物触碰等统统白费。

不过这仍然存在一个致命的问题：**老玩家问题**。这几乎是每个 MC 议题都会谈到的问题。到了后期，如果人人都是这样满年龄，也会使插件丧失意义。因此，我们需要在这种情况发生之前找到一个解决方案，或者现在就开始讨论。

**Comment by Subilan** [comment]
有些人觉得年龄和活跃度混淆了，的确如此。但是无论如何年龄不可能只由时间这一个因素来决定。因为它牵涉到权限。如果一个玩家能够只靠挂机就嫖来所有权限，后面我就不说了。

我认为可以花点时间了解一下 Essentials 的 API 来探究一个玩家的 AFK 状态，或者直接使用插件自己的方法进行判定。由此来杜绝玩家无意义挂机所带来的不应得好处。

**Comment by Sapherises** [comment]
> 我认为可以花点时间了解一下 Essentials 的 API 来探究一个玩家的 AFK 状态

据我所知，ess的AFK状态应该是可以获取到的，因为很多插件都有基于ess的AFK来判断是否给予物品奖励，比如每日在线奖励就可以根据ess的AFK来，所以应该是有AFK的API的，但是这又有个问题：玩家可能会制作挂机池来防止自己AFK之类的，所以我觉得如果可行的话，可以自己写一套判断标准，但是这样会增加工作量和推迟插件上线时间

**Comment by Subilan** [comment]
> > 我认为可以花点时间了解一下 Essentials 的 API 来探究一个玩家的 AFK 状态
> 
> 据我所知，ess的AFK状态应该是可以获取到的，因为很多插件都有基于ess的AFK来判断是否给予物品奖励，比如每日在线奖励就可以根据ess的AFK来，所以应该是有AFK的API的，但是这又有个问题：玩家可能会制作挂机池来防止自己AFK之类的，所以我觉得如果可行的话，可以自己写一套判断标准，但是这样会增加工作量和推迟插件上线时间

是这样的，因为我最近的 BQ 以及家里出现的状况，这个插件最早也得八月份。

如果等不过来大可以让常姐姐来写，就当我只是话题的参与者。说实话，我也不想到这种地步 :(

**Comment by Sapherises** [comment]
> 目前讨论出的结果我个人比较倾向于一个静态的最高年龄限制，到达此年龄后不再变动，但是仍然留有灵活的空间。因此服务器可以先设置一个基本年龄，例如 100，当出了新的内容**必须**在年龄限制上做手脚时，就可以一步步扩大，当然我们自己心里得有数到底最高可以到多少。

我也比较赞同限定一个固定的最高的年龄，这样对于当前讨论来说是工作量和可玩性的最优解。不过老玩家的确是个难题，我计划是在后面学习想皇室战争那样玩家升级到最高级以后再获得的经验转换成点数来兑换一些外观效果，而如何转换到sotap就以后再说8

**Comment by Sapherises** [comment]
> > > 我认为可以花点时间了解一下 Essentials 的 API 来探究一个玩家的 AFK 状态
> > 
> > 
> > 据我所知，ess的AFK状态应该是可以获取到的，因为很多插件都有基于ess的AFK来判断是否给予物品奖励，比如每日在线奖励就可以根据ess的AFK来，所以应该是有AFK的API的，但是这又有个问题：玩家可能会制作挂机池来防止自己AFK之类的，所以我觉得如果可行的话，可以自己写一套判断标准，但是这样会增加工作量和推迟插件上线时间
> 
> 是这样的，因为我最近的 BQ 以及家里出现的状况，这个插件最早也得八月份。
> 
> 如果等不过来大可以让常姐姐来写，就当我只是话题的参与者。说实话，我也不想到这种地步 :(

8月份的话其实可，年龄是我计划的一个重要玩法，但不是全部，我可以先弄其他的东西（也有够我弄的了）

**Comment by Subilan** [comment]
> > > > 我认为可以花点时间了解一下 Essentials 的 API 来探究一个玩家的 AFK 状态
> > > 
> > > 
> > > 据我所知，ess的AFK状态应该是可以获取到的，因为很多插件都有基于ess的AFK来判断是否给予物品奖励，比如每日在线奖励就可以根据ess的AFK来，所以应该是有AFK的API的，但是这又有个问题：玩家可能会制作挂机池来防止自己AFK之类的，所以我觉得如果可行的话，可以自己写一套判断标准，但是这样会增加工作量和推迟插件上线时间
> > 
> > 
> > 是这样的，因为我最近的 BQ 以及家里出现的状况，这个插件最早也得八月份。
> > 如果等不过来大可以让常姐姐来写，就当我只是话题的参与者。说实话，我也不想到这种地步 :(
> 
> 8月份的话其实可，年龄是我计划的一个重要玩法，但不是全部，我可以先弄其他的东西（也有够我弄的了）

那时间上的问题解决了。

现在还有什么内容上的问题吗？有或者没有我都先睡了，欢迎给我留言。

**Comment by Subilan** [comment]
Ageing 项目：
~~https://github.com/Subilan/Ageing~~
https://github.com/sotapmc/Ageing
