### ISSUE TITLE
关于本次拍卖活动的问题反馈

### ISSUE THREAD

**Issue by Subilan** [sotapmc/Discussion#5]
很明显我们可以看出本次拍卖活动的问题出在哪里，在这里我归纳一下。可能并不完整，大家一起讨论、补充和解决即可。本反馈不针对任何 SoTap 玩家，仅仅是为了提高将来的拍卖体验。

- 一些玩家在本场拍卖刚刚开始时便给出了远高于起步价的「不合理」价格。例如一些平淡的资源却
能被此举炒上了几千甚至万级别的报价。
- 一些玩家疑似带节奏，**点名批评凉席**。带节奏分为两种
    - 第一种是很确信自己的不合理价格会被跟上，所以肆无忌惮发出来
    - 第二种是故意发出来以后秒撤回，引导价格方向
- 玩家很容易「被带节奏」，例如出现了很高的价格，便要拼命去争，即使对自己并不是很重要
- 一些服务器财产比较充裕的玩家即使物品本身对自己不重要也要参与进来，提出高价，扰乱市场
- 一些玩家可能对拍卖不以为然，以为只是游戏而无需重视

![image](https://user-images.githubusercontent.com/36447840/82147069-cca73480-987f-11ea-8b30-f34bba1ccaad.png)
![8Z1O{OZKKGJ4E _CT1$43UR](https://user-images.githubusercontent.com/36447840/82147215-ce252c80-9880-11ea-8908-8a3e81b5f7d8.jpg)

这些情况无论怎么说都是非常不合适的、扰乱市场的。会让拍卖失去意义。你可能要问拍卖的意义是什么？

![image](https://user-images.githubusercontent.com/36447840/82147328-8c48b600-9881-11ea-9e25-e776e3bd9d0c.png)

一般来说拍卖是用于为一些不好定价的东西来「定价」，比如收藏品、艺术品等。然而我们卖的又不是这类东西。对于一些平凡的物品的拍卖，更多倾向于的是「玩法」。既然说到了玩法，对普通物品的拍卖的本质就是体验这种「博弈」的快感，这同样适用于本次以及以后的所有拍卖活动。

可能又要问，既然是为了体验博弈的快感，为什么还要考虑到这么多的问题呢？难道不是出价越高越激烈越好玩吗？并不是。因为我们最终是要把这些东西卖出去的，如果一上来就给出这么多不合理的价格，势必会让那些真心想要的玩家感到失望，但是并不能说什么。**服务器不是现实社会。**

![FR {I336_)M%TOF TE0 MPL](https://user-images.githubusercontent.com/36447840/82147373-e9dd0280-9881-11ea-8ebd-34e87125449d.png)

所以我想说，我们是否需要一个策略来改变第一次这种「踩坑」的情况。在回复中我会给出我已经考虑到的几种解决办法。

**Comment by Subilan** [comment]
1. 解决玩家故意秒撤引导报价：**禁止撤回报价**。全程录屏记录并归档，以后每次如此。任何报价无论撤回与否都会被记录下来，并当作正常报价处理。在这里需要说一下，如果是在拍卖时，主持人发现有人撤回报价，不必多说，将撤回的内容当作正常报价处理即可。如果报价人对此有疑问，可以出示录像作为证据。
2. 让所有玩家都知道要为自己的报价负责：**严惩无法支付的情况**。无意或有意的报价过高导致的自身账户无法支付将追究责任，不仅仅是欠款那么简单。做到双倍欠、三倍欠，撤销某些权限等。

**Comment by AnonymityW** [comment]
这个感觉有点廉价.jpg

**Comment by Subilan** [comment]
另外，为了防止信息无法辨认，我认为应当限制当前这种「发出去看见了以后撤回」的聊天模式。虽然无伤大雅，留下来的只是满屏的 XXX 撤回了一条消息，但是仍然会对过程造成一定的影响。

同时，对于拍卖过程中遇到的问题，需要玩家自己私下解决（例如，XXX 物品有什么用这类对拍卖无任何影响的问题），亦或者是私下联系 / 结束后联系管理员进行解决，避免扰乱群内聊天秩序。

如果觉得规则的束缚会导致群内在拍卖时段失去活跃度，可以考虑另创拍卖群，平时禁言，仅需要时开放使用。

**Comment by Subilan** [comment]
细节问题：
![~K8D%0IGI}%R5B@HZON9N~3](https://user-images.githubusercontent.com/36447840/82148053-9ae49c80-9884-11ea-9933-1ecacb66fbe1.png)

对于网络延迟造成不可避免价格规律异常，主持人仅需取其中最高价。

**Comment by Subilan** [comment]
建议添加一个额外的参数：**最高步进价**
![image](https://user-images.githubusercontent.com/36447840/82148238-9b316780-9885-11ea-8657-79064881420d.png)

传统的步进价将充当最小值，最高步进价充当最大值，玩家叠加价格只能在此区间内，否则视为无效。

**Comment by constant137** [comment]
关于最高进步价的进一步讨论：
首先我也同意需要定义一个最高进步价格，但是这里还存在一些问题。这个最高进步价最好不要是一个固定的值。从两点来体现：

1. 某物品起步价100，最高进步价100。但是随着拍卖的进行，它很可能变成500，甚至上千。这时候再用100来限制每次最高的加价就不合理了。
2. A物品起步100，最高进步100；B物品起步500，最高进步价也是100。这样显然也是不合理的。

上面两个例子说明这个最高进步价应该和物品当前拍卖的价格存在一定的关系，不能一直保持不变，不同的物品之间也需要灵活的调整。

这里给出一个建议是，单次加价不能超过当前价格的 x%，这里的 x应该定多少需要继续讨论。个人倾向的是x=100，这样操作起来也比较方便。

**Comment by Subilan** [comment]
补充离谱例子![NVBW 0GGA`(T 3)L6E8O8FR](https://user-images.githubusercontent.com/36447840/82151698-5e6a6e00-988f-11ea-8421-9dbd2b3a0857.jpg)

![image](https://user-images.githubusercontent.com/36447840/82151572-9de48a80-988e-11ea-84dc-e918b2fa3e8b.png)
![image](https://user-images.githubusercontent.com/36447840/82151690-54486f80-988f-11ea-8252-645d4e6b9cf6.png)

**Comment by Subilan** [comment]
# 反对价格垄断, 从我做起, 从 `Majesty_W` 做起!

**Comment by Subilan** [comment]
@constant137 主要是想让玩家不用在出价的时候那么费力计算，一个固定的区间是再简单不过的了。百分比的确更加合理，但是我们似乎只能从一些比较好算的百分比里面挑选。`100%` 我认为是可以的，不过根据情况也可以选择 `50%`、`25%`、`75%` 这些。实际上 `25%` 和 `75%` 对于有些人来说就有些难以瞬间计算了。

**Comment by AnonymityW** [comment]
Majesty_W跟我AnoymityW有什么关系.jpg

**Comment by Sapherises** [comment]
各位的提议都非常不错，i了i了

**Comment by Subilan** [comment]
> Majesty_W跟我AnoymityW有什么关系.jpg

![LSIZ}MLS$EWU}QE2KAG1_XY](https://user-images.githubusercontent.com/36447840/82152611-0a628800-9895-11ea-935a-a16de0cb146d.png)

**Comment by Subilan** [comment]
在？怎么 No response 了？
