### ISSUE TITLE
关于 Ageing 以及其衍生插件的想法的讨论

### ISSUE THREAD

**Issue by Subilan** [sotapmc/Discussion#6]
从[上次](https://github.com/sotapmc/Discussion/issues/4)谈起 Ageing 到这次真正开始讨论它已经过去了不知道*多少*个月... 不过无所谓了。之前的库已经删了哦，那么我们这回就重新开始吧。

根据我现在的想法，Ageing 不再会是一个以「计算」为主要目的的插件，而是以「统计」为主要目的。大概率可以充当一种服务器核心插件的角色，也有利于将来对 SoTap 插件生态系统的整体规划。以下来详细说说我的想法。

## 解释「计算」与「统计」

从字面上就可以很容易看出这两者之间的联系，即通过计算，进行统计。所有的统计以计算为基础，所有的计算都会汇成最终的统计结果。计算就好比是一个过程，通过我们预想的方式和计划，通过单或多方面的反馈将复杂的不规则数据量化。对于计算，有下列例子可以参考：

- 先前 Ageing 是打算根据玩家挖矿、在线时长等等因素来进行考虑，实现对用户等级（年龄）的提高
- 做任务做完领奖励，我们大概会得到一些经验，这也是计算
- 比赛其实也是计算，因为它也属于将不规则数据（比赛规则衍生出的行为模式）量化（最终的排名）

统计就简单了，就是把计算结果给汇总。所以统计我们要做的工作都不怎么吃脑力，通俗来讲就是没有创意的意思。这不是贬义，就好比数学，我们根本没必要用修辞手法也能写出来让人耳目一新的巨著。相比于那些需要修饰的部分，统计更像是在原则上就不需要它们。

## 具体的想法与基本实施

具体的想法嘛... 其实再说多了就有些多余或者说啰嗦了。那么就简单说一下吧。由于 Ageing 咕咕咕的实在是太厉害导致 @Sapherises 所计划好的游戏内容没能及时得到实现，再这样拖下去不仅是让人感到更加着急更会辜负玩家的付出。那么这样一个计划就有实施的必要性了。

至于为什么 Ageing 要抛弃原先的**计算+统计**模式呢？大概就是因为创意的缺失吧。不过问题不大。我认为与其把一些模糊的概念强制糅合在一起放在这么一个独立的插件里面（甚至有些突兀），倒不如把它有规律地分配到各个方面去更好、更具体地实现，然后借此来发展我们自己的插件生态。

就当作是一种尝试吧。以 Ageing 为中心的生态系统的第一个成员将会是任务系统，然后这个系统的实施方案需要 sa 自己写（无慈悲）。

## 关于进一步的讨论

搞快点

**Comment by Sapherises** [comment]
![Screenshot_20200724-211006](https://user-images.githubusercontent.com/54004190/88394473-18cba380-cdf2-11ea-9d8d-16ec21ae9a42.jpg)
这是我参考荒野乱斗任务系统的灵感。就是其通过配置文件，我们可以自定义任务内容，添加或删减任务，和编辑任务，而且会实时自动更新其改动（参考我们当前用的菜单系统）。  
然后至于其任务内容，可以是挖矿，挖指定方块多少个，繁殖多少只动物，或者收获多少小麦之类的。当然还可以探索指定的生物群系或者，到达多少个指定的生物群系。还有和村民交易多少次，合成多少个指定物品等等。这些任务内容都是建议，要看su有没有能力添加这种类型的任务了。  
然后参看这幅图，我们可以分为每日任务和每周任务，每日任务比较简单，并且有较短时间限制，在下次刷新前没做完就会自动取消掉任务然后刷新新任务。而每周任务则每个月才刷新一次。每日任务所获得的点数比较少，任务较为简单，而每周任务则会难做一点，但是获得的任务点数较多。然后再看看这幅图的上方，通过积累到一定的点数来进化到下一等级。  
每日任务和每周任务的配置文件建议分开，等于两个卡池，提前设置好很多任务放入相应卡池，每到刷新时间到的时候自动从对应的卡池抽取任务。每日任务是2个，每日刷新，没做完也会被刷新掉，每周任务是每周刷新出4个，但是没做完的会一直保留积累一个月，然后没做完的任务才会被自动清空。  
然后刷新的建议是每个用户自己随机刷新，等于每个人的每日任务和每周任务刷新出来不是完全相同的。  
如果可以的话，还可以新加一个特变任务的卡池，比如到特定节假日会刷新出的限定任务。  
我们还可以出一些道具，比如一段时间内完成任务奖励的点数翻倍？或者直接卖翻倍点数的量，比如接下来获得的1000点数会翻倍之类的

**Comment by Subilan** [comment]
好的... 看了一下，做起来还是比较麻烦，不过都可以做。因为目前还是比较着急的状态，所以我会临时挑选出一部分功能来做。比如

- 通过配置文件来添加、删减和编辑任务（短时间内没时间研究自动更新，不过就只需要 `reload`）
- 添加任务的类型，包括
    - 挖指定方块指定数量个（收获小麦、砍伐树木和挖矿都包含在内）；
    - 繁殖动物指定数量对；
    - 探索指定生物群系指定数量个；
    - 与村民交易指定数量次；
    - 合成指定物品指定数量个；
- 每日任务的大概轮廓

对于其它的没有列在上面的列表中的，则是短时间内无法实现的内容。在这里，短时间指的是与 Ageing 共同开发所占用的时间。对于后面较为复杂的「卡池系统」则可以留到后期继续钻研和完善。

上述列表中也许会含有一些 Flag，但是只要有 API 或者骚操作可以做的，我都会去尝试实现。MC 这个东西放到编程上就比较本质，因此有些时候没必要思考那么复杂。就比如挖矿、挖指定方块和收获小麦，这三件事情写成代码就只是一行，也可以说是大大减轻了工作量。

**Comment by Subilan** [comment]
closed owing to no reply
